export function generateAgentsMarkdown(
  aiTargets: string[],
  severity: string,
  projectContext: string,
  projectStack: string
): string {
  return `# Global Agent Guidelines (Sauron CLI)

**Targets:** ${aiTargets.join(', ')}
**Severity:** ${severity}

## Project Context
${projectContext}

## Tech Stack
${projectStack}

## Golden Rule (Write Obligation)
All agents operating in this repository are strictly OBLIGATED to document any architectural changes, business rules, or state mutations in the corresponding \`.sauron\` and \`.agents\` folders. Passive reading without documentation is considered a compliance violation.

*Automatically generated by Sauron CLI.*
`;
}
